### ISSUE TITLE
Some strange problem :  sh: /home/Boos/.conky/disk_temp.sh: No such file or directory

### ISSUE THREAD

**Issue by xxzozaxx** [raphael141714/personnal-Conky#1]
**What Am i have ?**

~/conky
~/conky/graps.lua
~/conky/disk_tmp.sh
~/.conkyrc

**But** when I run conky in terminal it return : 
**
conky: desktop window (127) is root window
conky: window type - desktop
conky: drawing to created window (0x3800001)
conky: drawing to double buffer
sh: /home/Boos/.conky/disk_temp.sh: No such file or directory
conky: llua_getstring: function conky_TIME_clock didn't return a string, result discarded
conky: llua_getstring: function conky_UPTIME_timer didn't return a string, result discarded
conky: obj->data.i 5 info.cpu_count 4
conky: attempting to use more CPUs than you have!
**
and nothing happen

**Comment by raphael141714** [comment]
> "conky: desktop window (127) is root window
conky: window type - desktop
conky: drawing to created window (0x3800001)
conky: drawing to double buffer"

Standard stuff so far.

>  "sh: /home/Boos/.conky/disk_temp.sh: No such file or directory"

I bet it's a permission issue.  
A `chmod +x /home/Boos/.conky/disk_temp.sh` should do the trick.

> "conky: llua_getstring: function conky_TIME_clock didn't return a string, result discarded
conky: llua_getstring: function conky_UPTIME_timer didn't return a string, result discarded"

That's a warning that my Lua functions don't return anything printable. You can safely ignore it.

> "conky: attempting to use more CPUs than you have!"

It just means that the script is trying to display the results of 8 cpu threads, but you don't have 8 threads.
`$ less /proc/cpuinfo` tells you all you need to know about your cpu.
It seems that it's a 4 threads one.
I'll push other scripts for worse cpus than mine tomorrow, and I'll update my README.md about installation.

> "and nothing happen"

When conky has issues, it simply doesn't print anything. And it doesn't parse further than where it crashed.

**Comment by xxzozaxx** [comment]
@raphael141714  thank you so much , every thing is ok **Now**  🎉

**Comment by raphael141714** [comment]
I haven't yet pushed my promised code! But you're welcome :)
Stay tuned to have a more personnalized script
